### PR TITLE
Support proxying with TLS client certificates in Nginx

### PR DESCRIPTION
**Pull request by grkvlt**

### CODE REVIEW

**Comment by aledsage-tmp** [comment]
@grkvlt Can you add a test as well please - see https://github.com/apache/brooklyn-library/blob/67a4dda36fcc0eaa628a5a887bdb07f953e06610/software/webapp/src/test/java/org/apache/brooklyn/entity/proxy/nginx/NginxHttpsSslIntegrationTest.java for existing nginx tests that are similar.

**Comment by grkvlt** [comment]
@aledsage not sure how easy the test will be, since will need to configure tomcat (?) for client certificate auth, as well as generating a client certificate for the server that is running the test, so that it validates. I have tested this many times as a proxy to a Docker Swarm that uses client certificate authentication, but not sure how to replicate that in a test.

**Comment by Graeme-Miller** [comment]
LGTM, but I agree with Aled that testing would be beneficial. Andrew did you investigate further how to do this?

**Comment by aledsage** [comment]
jenkins build failure is unrelated - @grkvlt is kicking it off again:

```
Parsing POMs
Downloaded artifact http://repository.apache.org/snapshots/org/apache/brooklyn/brooklyn-parent/0.10.0-SNAPSHOT/maven-metadata.xml
Downloaded artifact http://repository.apache.org/snapshots/org/apache/brooklyn/brooklyn-parent/0.10.0-SNAPSHOT/brooklyn-parent-0.10.0-20160719.223024-76.pom
Downloaded artifact http://repository.apache.org/snapshots/org/apache/brooklyn/brooklyn-server/0.10.0-SNAPSHOT/maven-metadata.xml
Downloaded artifact http://repository.apache.org/snapshots/org/apache/brooklyn/brooklyn-server/0.10.0-SNAPSHOT/brooklyn-server-0.10.0-20160719.223502-76.pom
Failed to transfer Could not find metadata org.apache.brooklyn:brooklyn-parent:0.10.0-SNAPSHOT/maven-metadata.xml in clojars.org (http://clojars.org/repo)
Failed to transfer Could not find metadata org.apache.brooklyn:brooklyn-server:0.10.0-SNAPSHOT/maven-metadata.xml in clojars.org (http://clojars.org/repo)
Failed to transfer Could not find metadata org.apache.brooklyn:brooklyn-parent:0.10.0-SNAPSHOT/maven-metadata.xml in oracle (http://download.oracle.com/maven)
Failed to transfer Could not find metadata org.apache.brooklyn:brooklyn-server:0.10.0-SNAPSHOT/maven-metadata.xml in oracle (http://download.oracle.com/maven)
Modules changed, recalculating dependency graph
Build timed out (after 40 minutes). Marking the build as aborted.
Build was aborted
Putting comment on the pull request
Finished: ABORTED
```

**Comment by aledsage** [comment]
@grkvlt I agree this is too hard to write a test here for! We'd need to generate a certificate for the specific IP address of the server that the test is running against, then have some software component (e.g. etcd or swarm-node) that requies tls, and then configure our nginx to talk to that.

This is being tested in a downstream project. The pragmatic thing to do is to merge this, and rely on the downstream project to regression test it for us. It's a fairly niche use-case anyway.

Merging now that jenkins has completed.

**Pull request merged**
