### PR TITLE
BROOKLYN-272: disable failing non-deterministic tests

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by neykov** [comment]
+1

Can we include the tests failing in the windows build as well. Here are a couple of recent failures:

* https://builds.apache.org/view/Brooklyn/job/brooklyn-master-windows/109

```
testFetchApplicationsAndEntity(org.apache.brooklyn.rest.resources.ApplicationResourceTest)  Time elapsed: 0.073 sec  <<< FAILURE!
java.lang.AssertionError: expected [4] but found [3]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at org.apache.brooklyn.rest.resources.ApplicationResourceTest.testFetchApplicationsAndEntity(ApplicationResourceTest.java:387)


Results :

Failed tests: 
  ApplicationResourceTest.testFetchApplicationsAndEntity:387 expected [4] but found [3]
```
* https://builds.apache.org/view/Brooklyn/job/brooklyn-master-windows/117

```
AssertionError: entity=FeedExceptionEntityImpl{id=dYG0SKbP}; attribute=Sensor: flag (java.lang.Boolean) expected [false] but found [true]
	at org.apache.brooklyn.test.Asserts.fail(Asserts.java:721)
	at org.apache.brooklyn.test.Asserts.failNotEquals(Asserts.java:114)
	at org.apache.brooklyn.test.Asserts.assertEquals(Asserts.java:436)
	at org.apache.brooklyn.core.entity.EntityAsserts.assertAttributeEquals(EntityAsserts.java:54)
	at org.apache.brooklyn.core.entity.EntityAsserts$1.run(EntityAsserts.java:70)
	at org.apache.brooklyn.test.Asserts$RunnableAdapter.call(Asserts.java:1277)
	at org.apache.brooklyn.test.Asserts.succeedsEventually(Asserts.java:930)
	at org.apache.brooklyn.test.Asserts.succeedsEventually(Asserts.java:854)
	at org.apache.brooklyn.core.entity.EntityAsserts.assertAttributeEqualsEventually(EntityAsserts.java:67)
	at org.apache.brooklyn.core.feed.PollerTest.testFeedContinuesWhenPollerThrows(PollerTest.java:65)

2016-05-19 18:00:39,800 INFO  Brooklyn shutdown: stopping entities [TestEntityImpl{id=gMtZBj5M}, TestEntityImpl{id=KJ03W2e9}, BlockingEntityImpl{id=ATsLvkYo}]

Results :

Failed tests: 
org.apache.brooklyn.core.feed.PollerTest.testFeedContinuesWhenPollerThrows(org.apache.brooklyn.core.feed.PollerTest)
  Run 1: PASS
  Run 2: PollerTest.testFeedContinuesWhenPollerThrows:65 » PropagatedRuntime failed suc...
```

**Comment by aledsage** [comment]
Thanks @neykov 

I've added the disabling of `ApplicationResourceTest.testFetchApplicationsAndEntity` to https://github.com/apache/brooklyn-server/pull/147. `PollerTest.testFeedContinuesWhenPollerThrows` was already disabled there.

**Comment by neykov** [comment]
Thanks @aledsage. Could you change this one to the `Broken` group as well, then good to merge.

**Comment by aledsage** [comment]
Thanks @neykov - merging.

**Pull request merged**
