### PR TITLE
ZooKeeper ensemble fixes

### PR DESCRIPTION
**Pull request by sjcorbett**
* Fixes ZooKeeper ensembles by ensuring that each node has a different id. 
* Improves live tests to test that data can be written and read back.
* ZooKeeperNodes publish their host and port on main.uri
* ZooKeeperEnsemble aggregates its member's main.uris into a list and combines them into a comma-separated string at `zookeeper.endpoints`.

### CODE REVIEW

**Comment by sjcorbett** [comment]
These changes depend on https://github.com/apache/brooklyn-server/pull/439.

**Comment by sjcorbett** [comment]
The build failed because it's missing the dependencies mentioned in brooklyn-server.

**Comment by drigodwin** [comment]
Looks good & tested on AWS. We probably also need to extend the tests at [brooklyn-zookeeper-ensemble](https://github.com/brooklyncentral/brooklyn-zookeeper-ensemble/) at some point to better identify issues.

**Comment by neykov** [comment]
Thanks for reviewing and testing @drigodwin. Merging.

**Pull request merged**
