### PR TITLE
DO NOT MERGE - for testing PR builds

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-library-pull-requests-pipeline/3/

**Comment by aledsage** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-library-pull-requests-pipeline/4/

**Comment by aledsage** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-library-pull-requests-pipeline/5/

**Pull request closed without merging**
