### PR TITLE
corrects broken composer palette icon for Artemis

### PR DESCRIPTION
**Pull request by frogfather**
The Artemis logo on the composer palette was a hotlink from the ActiveMQ site. The link was no longer valid. Added static image to brooklyn-library and adjusted path.

### CODE REVIEW

**Comment by duncangrant** [comment]
I guess we should use the same log for all the activemq entites?  So might be better to update the existing one?

**Comment by frogfather** [comment]
> I guess we should use the same log for all the activemq entites? So might be better to update the existing one?

Done!

**Comment by ahgittin** [comment]
I'd be inclined to remove `artemis-logo.png` and simply reference the updated activemq for that one.

@frogfather do you have an Apache ICLA?

i'll update the notice metadata to note we are including that file in our source dist.

**Comment by ahgittin** [comment]
looks good.  i've added a comment to our notices about use of logos, in a separate PR.

as soon as @frogfather has an ICLA approved i think this can be merged

**Comment by ahgittin** [comment]
@frogfather you're listed with an ICLA, so merging

**Pull request merged**
